runtime: php72
handlers:

- url: /(.+\.(gif|png|jpg|svg|webp|jpeg|js|php|css))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg|webp|jpeg|js|php|css)$

- url: /www/css
  static_dir: css

- url: /www/js
  static_dir: js
- url: /www/images
  static_dir: images
- url: /src
  static_dir: src
- url: /
  script: auto
- url: /(.\.php)$
  script: auto
- url: /(.\.js)$
  script: auto
- url: /(.\.css)$
  script: auto