runtime: php
api_version: 1

handlers:
- url: /(.*\.(htm$|html$|css$|js$))
  static_files: \wwww
  upload: (.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /www/css
  static_dir: css

- url: /www/js
  static_dir: js

- url: /www/images
  static_dir: images

- url: /www/secret
  static_dir: secret

- url: /.*
  static_dir: test.php

- url: /.*
  static_dir: test.php
- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: \wwww
  upload: (.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.+)
  script: \www

- url: /.*
  script: index.php